use std::{env, path::PathBuf};

fn main() {
    cc::Build::new()
        .cpp(true)
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/arm/arm.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/gsu/gsu.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/hg51b/hg51b.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/lr35902/lr35902.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/r65816/r65816.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/spc700/spc700.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/processor/upd96050/upd96050.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/interface/interface.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/system/system.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/scheduler/scheduler.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/memory/memory.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/cartridge/cartridge.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/cpu/cpu.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/ppu/ppu.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/apu/apu.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/cheat/cheat.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/gb/video/video.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/interface/interface.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/base/satellaview/satellaview.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/system/system.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/controller/controller.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/cartridge/cartridge.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/cheat/cheat.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/memory/memory.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/icd2/icd2.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/bsx/bsx.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/nss/nss.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/event/event.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/sa1/sa1.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/superfx/superfx.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/armdsp/armdsp.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/hitachidsp/hitachidsp.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/necdsp/necdsp.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/epsonrtc/epsonrtc.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/sharprtc/sharprtc.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/spc7110/spc7110.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/sdd1/sdd1.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/obc1/obc1.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/hsu1/hsu1.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/msu1/msu1.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/slot/satellaview/satellaview.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/slot/sufamiturbo/sufamiturbo.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/dsp1/dsp1.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/dsp2/dsp2.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/dsp3/dsp3.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/dsp4/dsp4.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/cx4/cx4.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/st0010/st0010.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/chip/sgb-external/sgb-external.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/alt/cpu/cpu.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/alt/smp/smp.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/alt/dsp/dsp.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/sfc/alt/ppu-performance/ppu.cpp")
        .file("bsnes-mercury-wrapper/bsnes-mercury/libco/libco.c")
        .file("bsnes-mercury-wrapper/wrapper.cpp")
        .define("HAVE_POSIX_MEMALIGN", None)
        .define("PROFILE_PERFORMANCE", None)
        .include("bsnes-mercury-wrapper/bsnes-mercury")
        .include("bsnes-mercury-wrapper/bsnes-mercury/sfc")
        .include("bsnes-mercury-wrapper/bsnes-mercury/libco")
        .define("STDC_HEADERS", None)
        .define("__STDC_LIMIT_MACROS", None)
        .define("__LIBRETRO__", None)
        .define("SFC_LAGFIX", None)
        .warnings(false)
        .compile("bsnes-mercury-wrapper");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindgen::Builder::default()
        .header("bsnes-mercury-wrapper/wrapper.h")
        .allowlist_file("bsnes-mercury-wrapper/wrapper.h")
        .generate()
        .unwrap()
        .write_to_file(out_dir.join("bindings.rs"))
        .unwrap();
}
